CREATE TABLE users(
  user_no INT AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(20) COLLATE utf8mb4_bin NOT NULL UNIQUE,
  password_hash VARCHAR(200) NOT NULL
);

CREATE TABLE todos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(20) NOT NULL,
  content VARCHAR(200) NOT NULL,
  priority_content VARCHAR(3) NOT NULL,
  limit_date DATE NOT NULL,
  public_on BOOLEAN NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  user_no INT NOT NULL,
  FOREIGN KEY  (user_no) REFERENCES users(user_no)
);
